module.exports={
    kohls_cash_what:"http://kohls.com/wallet/cash/what",
    kohls_cash_how:"http://kohls.com/wallet/cash/how",
    kohls_cash:"http://kohls.com/wallet/cash",
    rewards_points:"http://kohls.com/wallet/rewardpoints",
    rewards_activity:"http://kohls.com/wallet/rewards/activity",
    kohls_deals:"http://kohls.com/deals",
    store_tools:"http://kohls.com/storetools",
    search_req:"http://kohls.com/deals"
};